INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (0, 'UNKNOWN');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (1, 'Global Structures Ltd.');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (2, 'BuildRight Incorporated');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (3, 'Skyline Builders');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (4, 'Pinnacle Construction Co.');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (5, 'Foundation Enterprises');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (6, 'EcoBuilding Group');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (7, 'Urban Development Inc.');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (8, 'Harmony Housing Solutions');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (9, 'Blueprint Builders');
INSERT INTO y_khudorozhkov.building_organization (id, name) VALUES (10, 'Premier Infrastructure LLC');
