INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (0, 'UNKNOWN', 0, 0);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (60, '1234 Riverside Drive', 21, 91);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (61, '5678 Greenbelt Rd', 22, 92);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (62, '91011 Silver Line Blvd', 23, 93);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (63, '1213 Maple Street', 24, 94);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (64, '1415 Oak Avenue', 25, 95);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (65, '1617 Pine Road', 26, 96);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (66, '1819 Elm Street', 27, 97);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (67, '2021 Birch Parkway', 28, 98);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (68, '2223 Cedar Lane', 29, 99);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (69, '2425 Spruce Way', 30, 100);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (70, '2627 Aspen Court', 31, 101);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (71, '2829 Walnut Street', 32, 102);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (72, '3031 Cherry Avenue', 33, 103);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (73, '3233 Mahogany Blvd', 34, 104);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (74, '3435 Basswood Road', 35, 105);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (75, '3637 Alder Drive', 36, 106);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (76, '3839 Willow Way', 37, 107);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (77, '4041 Sycamore Street', 38, 108);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (78, '4243 Dogwood Drive', 39, 109);
INSERT INTO y_khudorozhkov.building_site (id, address, management_id, manager_id) VALUES (79, '4445 Fir Street', 40, 110);
