INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (0, 'UNKNOWN', 0);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (21, 'Alpha Operations', 51);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (22, 'Beta Development Group', 52);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (23, 'Gamma Building Authority', 53);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (24, 'Delta Construction Syndicate', 54);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (25, 'Epsilon Urban Projects', 55);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (26, 'Zeta Industrial Solutions', 56);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (27, 'Eta Infrastructure Co.', 57);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (28, 'Theta Property Ventures', 58);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (29, 'Iota Environmental Design', 59);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (30, 'Kappa Public Works', 60);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (31, 'Lambda Residential Ltd.', 61);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (32, 'Mu Commercial Builders', 62);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (33, 'Nu Civil Engineering Firm', 63);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (34, 'Xi Regional Planners', 64);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (35, 'Omicron Construction Services', 65);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (36, 'Pi Tower Constructions', 66);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (37, 'Rho Roadwork Specialists', 67);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (38, 'Sigma Bridge Projects', 68);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (39, 'Tau Utility Networks', 69);
INSERT INTO y_khudorozhkov.construction_management (id, name, manager_id) VALUES (40, 'Upsilon Heritage Restorations', 70);
