INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (1, 'Crawler Crane', 152);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (2, 'Tower Crane', 153);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (3, 'Concrete Mixer', 154);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (4, 'Bulldozer', 155);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (5, 'Excavator', 156);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (6, 'Dump Truck', 157);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (7, 'Wheel Loader', 158);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (8, 'Compact Excavator', 159);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (9, 'Telehandler', 160);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (10, 'Skid-Steer Loader', 161);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (11, 'Mobile Crane', 162);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (12, 'Backhoe Loader', 163);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (13, 'Asphalt Paver', 164);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (14, 'Road Roller', 165);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (15, 'Trencher', 166);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (16, 'Pile Driver', 152);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (17, 'Sand Screener', 155);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (18, 'Grader', 158);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (19, 'Cement Pump Truck', 161);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (20, 'Track Loader', 164);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (21, 'Horizontal Drilling Machine', 153);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (22, 'Concrete Vibrator', 156);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (23, 'Forklift', 159);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (24, 'Pipe Layer', 162);
INSERT INTO y_khudorozhkov.construction_machinery (id, name, project_id) VALUES (25, 'Material Handler', 165);
