INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (0, 'UNKNOWN', 0, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (344, 'Alpha Engineering Group', 152, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (345, 'Beta Design Squad', 153, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (346, 'Gamma Structural Team', 154, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (347, 'Delta Construction Unit', 155, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (348, 'Epsilon Project Crew', 156, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (349, 'Zeta Development Team', 157, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (350, 'Eta Builders Collective', 158, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (351, 'Theta Engineering Corp', 159, 'MASTER');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (352, 'Iota Development Group', 160, 'TECHNICAL');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (353, 'Kappa Construction Squad', 161, 'TECHNICAL');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (354, 'Lambda Design Team', 162, 'TECHNICAL');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (355, 'Mu Structural Unit', 163, 'TECHNICAL');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (356, 'Nu Project Crew', 164, 'TECHNICAL');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (357, 'Xi Development Team', 165, 'TECHNICAL');
INSERT INTO y_khudorozhkov.engineer_team (id, name, project_id, type) VALUES (358, 'Omicron Builders Collective', 166, 'TECHNICAL');
