INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (0, 'UNKNOWN');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (1, 'Structural Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (2, 'Construction Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (3, 'Site Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (4, 'Civil Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (5, 'Geotechnical Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (6, 'Environmental Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (7, 'Water Resource Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (8, 'Transportation Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (9, 'Urban Planning Engineer');
INSERT INTO y_khudorozhkov.engineer_position (id, name) VALUES (10, 'Project Engineer');
