INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (0, 'UNKNOWN', 1);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (1, 'Cement', 250);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (2, 'Sand', 50);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (3, 'Gravel', 75);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (4, 'Steel Rebar', 450);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (5, 'Wood Planks', 200);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (6, 'Concrete Blocks', 300);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (7, 'Bricks', 150);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (8, 'Insulation', 220);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (9, 'Paint', 120);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (10, 'Glass Panes', 400);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (11, 'Electrical Wire', 85);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (12, 'Piping', 90);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (13, 'Roofing Tiles', 230);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (14, 'Floor Tiles', 110);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (15, 'Wallpaper', 60);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (16, 'Ceramic Tiles', 100);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (17, 'Plywood', 80);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (18, 'Decorative Stone', 350);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (19, 'Laminate', 160);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (20, 'Vinyl Flooring', 140);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (21, 'Asphalt', 180);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (22, 'Drywall', 55);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (23, 'Waterproofing Materials', 210);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (24, 'Adhesives', 70);
INSERT INTO y_khudorozhkov.material (id, name, cost) VALUES (25, 'Sealants', 45);
