apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-front
  labels:
    app.kubernetes.io/name: {{.Release.Name}}-front
spec:
  selector:
    app.kubernetes.io/name: {{.Release.Name}}-front
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.front.port}}
      targetPort: 80
      name: http