apiVersion: v1
kind: Secret
metadata:
  name: database-auth-{{.Release.Name}}
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
type: Opaque
data:
  databaseUser: {{printf "%s" .Values.secrets.database.user | b64enc}}
  databasePassword: {{printf "%s" .Values.secrets.database.password | b64enc}}
  databaseHost: {{printf "%s" .Values.secrets.database.host | b64enc}}
  databasePort: {{printf "%s" .Values.secrets.database.port | b64enc}}
  databaseName: {{printf "%s" .Values.secrets.database.name | b64enc}}