apiVersion: v1
kind: Secret
metadata:
  name: docker-auth-{{.Release.Name}}
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.images.repository.registry .Values.images.repository.username .Values.images.repository.password (printf "%s:%s" .Values.images.repository.username .Values.images.repository.password | b64enc) | b64enc }}
